### PR TITLE
Create Shreddedlabel.lua

### PR DESCRIPTION
**Pull request by DarkSmythe**
Shreddedlabel LUA for Feeorin NM

### CODE REVIEW

**Review by DarkSmythe — COMMENTED** [review]
changed directory to npcs as appropriate

**Review by Mizzguy — CHANGES_REQUESTED** [review]
The name is wrong

**Comment by DarkSmythe** [comment]
I thought I submitted right name

Sent from my Verizon, Samsung Galaxy smartphone

-------- Original message --------

**Review by Mizzguy — APPROVED** [review]
Approving now

**Pull request merged**
